[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "tarvalon-scraper"
version = "0.1.6"
description = "Tar Valon Library summary scraper & exporter [.md/.epub]"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "codewormer"}
]

dependencies = [
    "requests",
    "beautifulsoup4",
    "rich",
    "ebooklib",
    "markdown"
]


[project.scripts]
tarvalon = "tarvalon_scraper.cli:main"


[project.urls]
Homepage = "https://github.com/code7wormer/tar_valon_scraper"


[tool.setuptools.packages.find]
where = ["src"]